
services:
  mongodb:
    image: mongo:4.6.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  backend:
    build:
      context: ./backend

    environment:
      - MONGODB_URI: "mongodb://mongodb:27017"
    ports:
      - 1234:1234
