
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  fgc-statistics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fgc-statistics
    ports:
      - "1234:1234"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./data:/data/db
    restart: always
