
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - 1234:1234

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8080:3000"
