
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  backend:
    build:
      context: ./backend
    ports:
      - 1234:1234
