#Build stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn run build

#Production stage
FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json .

COPY --from=build /app/dist ./dist

CMD ["node", "dist/server.js"]